baseURL = ""
languageCode = "en-us"
title = "UX Day Graz 2017"
theme = "flashtheme"

canonifyurls = false 

relativeurls = true

sectionPagesMenu = "main"
DefaultContentLanguage = "en"


[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  recent_posts_number = 2
